### ISSUE TITLE
No IP being distributed

### ISSUE THREAD

**Issue by stricklandrbls** [Esser420/EvilTwinFramework#3] opened 2017-10-19 23:55 UTC
I have my DHCP set up as follows:
gateway: 192.168.2.1
ip_range: 192.168.2.5 - 192.168.2.254
server: 8.8.8.8 8.8.4.4

but whenever I have a device connect to my AP it's not leased an IP
[+] New connected client on 'test'-> ip: None, mac: fc:a6:67:da:32:79 (None)

I'm using an ALPHA adapter as my wlan1 AP and my internal wireless card as connection to the internet

**Comment by Esser420** [comment] 2017-10-25 18:50
I'm pretty sure it's not really an issue, I'll explain how this works: 

There is a thread that looks for connected clients by periodically parsing the output of: iw dev \<wifi interface\> station dump

Clients are listed here if they are past the Association phase of the communication, after that they still have to request an IP via DHCP. It happens that the output of the command is parsed before they request an IP.

You can see the attributed IP with "display connected_clients"

You can close the issue after you've verified it.

**Comment by stricklandrbls** [comment] 2017-11-02 14:53
When I type that command it does not output any devices although on the phone I'm using it's given an ip. Although it's given an ip I can't scan it on nmap and display connected devices outputs nothing.

**Comment by Esser420** [comment] 2017-11-06 15:11
Okay let me understand the problem a little better (the code for this part is simply not very good, have to take care of it).

The problem is not the internet connection, right? From what I understand, the client has internet connection, but you do not seem to have access to the client from the host machine?

Can you show me the output of: 

> ifconfig

> route -n

> iw dev \<name of wifi interface\> station dump

> nmap -P 192.168.2.0/24

The nmap command assumes that the ETF created that subnet with default configurations, change accordingly if you changed the  'gateway' parameter in the 'dnsmasqhandler' configurations.

What OS are you using? Is it a VM?

**Comment by Esser420** [comment] 2017-12-23 13:09
Closing due to inactivitiy.

**Closed** 2017-12-23 13:09 UTC
